### Site Settings ###
title: Sam Hedges
description: >-
  I'm an Aspiring Gameplay Programmer and Technical Artist 🕹️
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: Sam-Hedges/Sam-Hedges.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme: Sam-Hedges/Sam-Hedges.github.io
open_new_tab: true # Opens external URLs in new tab (works for posts, projects and navbar only)

# bundle exec jekyll serve --incremental

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/wip.html
  - pages/index.md

### Author Info ###
author:
  name: Sam Hedges
  image: assets/General/pfp.png
  # behance           : your_username
  # dribbble          : your_username
  email: sam.hedges.sh@gmail.com
  # facebook          : your_username
  github: Sam-Hedges
  # gitlab            : your_username
  # instagram: sam__hedges
  # kaggle            : your_username
  linkedin: sam-hedges-927476180
  # medium            : your_username
  # soundcloud        : your_username
  # spotify           : your_username
  # stackoverflow     : your_user_id
  # tumblr            : your_username.tumblr.com
  # twitch: samhedgesdev
  twitter: Sam_Hedges_
  # reddit: RetainedStar64
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###
disqus:
  shortname: Sam-Hedges-Portfolio # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: true # Set true to enable analytics
  google:
    tracking_id: G-Y71N2C8PPS

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false              


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
